version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: photo_bucket
      POSTGRES_PASSWORD: photo_bucket
      POSTGRES_DB: photo_bucket
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
